---
title: "From One Accountant to Another"
---

As I am writing this, I have been a CPA for 5 years and almost 10 years since I started working as an accountant. Like many of you, my job is mostly about getting numbers and reports from one side to another, hoping that people can have a more intelligent and productive life about decisions involving lots of dollar signs. I really enjoy playing these roles and I am amazed how good data are changing co-workers' and management's work life. For that matter, I want to bring programming literacy and analytical thinking to my fellow accountants so that we can endure the impact of big data and AI much better. Let me share with you a few of my own stories.

# How I Started...

My accounting career life isn't always fulfilling. Also just like many of you, I had many mundane things that no one else wanted to do. Poor data quality, complicated logic, repetitiveness, all trouble my accounting life left and right. I was quite functional with Excel, even praised by my boss and my-workers sometimes, but I still felt pulling my hair off from time to time. Here are a few common examples: 
    
  a) some elegant and impactful data visualization that can only live as my imagination;
    
  b) I could get one Excel workbook done but I need to repeat for 20 other similar Excel workbooks;

  c) data are in a database, on a webpage or PDF documents, but I didn't know how to pull them together. Friends at IT were always busy to save their world already...
    
It felt defeating, even maddening sometimes. I wanted to get to the accounting part, and yet, I just couldn't even activate my accounting skills because the data were just not there. I then began to realize Excel started becoming a bottleneck not a solution, regardless of how everyone else thought I were good with it. I lacked of: a) imagination of what's possible and b) the actual skillsets to design and implement solutions. 

Courtesy of COVID, when social life was overrated at best, a soul search put me a path to pursue a master degree in management analytics. It was quite some work for an accountant with zero computer science training or programming skills, but it was very much doable and the reward is immense. It provided my ammunition to change my work life. I have the conviction now, that the era where programming should be handled by "IT" or "specialists" is over. Analytics skills are well charted on the wall for accountants' future. I.e. it will be **a literacy requirement**. 

# Not Just Staff, Managers, Too...

Later on, I was pulled into different brainstorming sessions how to modernize workflows and better deliver accounting information. Data lake, OLAP cloud database, data modelling, ETL pipeline, tasks schedulers, Spark, Python/R ... they just don't seem to click well with the champions of the modernization projects. Yet, these concepts play fundamental role in their projects, because even Excel Macros can't save the day anymore. It then occurred to me that programming enables with me a whole set of literacy and analytical thinking. Managers who never experienced programming or develop analytical thinking will face challenges leading their future workforces, much less leading the change itself.

# What About Generative AI?

We can't ignore the power of Gen AI anymore. ChatGPT, Gemini, Claude... you name it, they are getting very good. Regardless of how good we are at asking, after all, we still don't know what we don't know. If Gen AI writes us some codes either error or don't yield properly, we still need to fix it. We can't just turn around and say, it's not my fault, it's the AI... still nothing gets done. Then what? If anything, I found it combining human knowledge and inspiration from AI is quite powerful sauce. That said, back to square one, we still need to learn some programming.

# It's Still Hard to Start...

I have talked to many fellow CPAs, and most feel they have no footing in analytics. Why data analytics changed my accounting life but not so much for the others? Why so many businesses or their finance/accounting team struggle to pull off business analytics projects and can't realize returns on their investment in analytics?

Good thing you are looking at an accountant, I relate this too well. A lot lie in the lack of technological literacy. Two folds on this:

  a) Most of the accountants are not equipped with data technology/programming at all through their formal edcuation. Analytics by definition involves programmatic processes, so it is hard for us start analytics or to lead modern business intelligence projects. After all, you can't be blamed for or be comfortable with what you don't know. 
  
  b) Most of analytics professionals and educators usually have mastery of their fields, and they cannot properly relate to accounting folks' learning needs and bridge them over properly. This usually leads to dismay learners. 
  
This consistent demand and supply awkwardness leaves the CPA community unattended long enough that accountants start feeling "left out", which is quite unfortunate.  

# My Final Encouragement to You...

My fellow accountants, you have gone through a lot to be come CPAs, so you definitely have the curiosity, intelligence and perseverance for data analytics. You just need a bit of hand-holding and a few leads, especially from one of your own: 
  
- to overcome the fear of the unknown - data technologies
  
- to make that first step to write their first line of codes

- to get their first project done, and eventually, 

- to strategize and lead their organizational analytics projects. 

I hope to be that person for you, to get you to make that first baby-step. Analytics changed my accounting life, it can change yours, too.

I have taught in colleges and universities for 6 years and counting. Education is more than just a gig for me, even more than I care admit. To me, getting paid to help others succeed is the best value propositions that I have heard. I fundamentally believe the role it plays for anyone to achieve their definition of success and pursue their desirable life. I have no intention to keep my knowledge and experience to myself, or at least, that would be a rather lonely world where I will have to start living in. Hopefully, not too long, you will feel in good hands.

Trust me, I am, by no means a genius and if I can do it, you can function in data analytics world, as well. 

Welcome to "Data Analytics For Accounting Folks", we are getting into the mysterious analytics world together, in a very folky way.

# What's Here for You...

***On the navigation pane, you will be able to find a selection of topics and sessions that I created and delivered before. I hope you will find something of great interests and values to you.***

If you like what you see and would like to collaborate on or to ask me to deliver something for you or your community, feel free to reach out through LinkedIn. You can reach me right here from this page through the LinkedIn logo (upper left corner, under the title).
