---
title: "Elevate Accounting with Analytics"
subtitle: Python Version
date: 2025-06-30
author: Jianyuan(Andy) Hu
---

## Description

This seminar provides hands-on experience in completing a comprehensive data project and is designed by accountants for accountants. Participants will transform a dataset into a professional report using open-source solutions: Python and Quarto, inspiring you to enhance your accounting workflows. We will delve into the mindset of analytics professionals and explore the synergy between analytics and accounting. The seminar will conclude with an overview of the current analytics and technology landscape, and how accountants can capitalize on these trends. This course is designed for those who have basic level of knowledge about Python or other syntax-driven analytical tools such as R and others.

## Key Takeaways

Upon completion of this course, you will understand:

- Introduction to Python: Learn the fundamentals of Python, an open-source general-purposed programming language and how to manage and set up Python to be productive.

- Adopting an Analytics Mindset: Explore essential concepts and key components of successful analytics projects. 

- Data Analytics with Python: Gain skills in designing modules for importing, exporting, processing and visualizing data using Python. 

- Report Creation with Quarto: Learn to build and publish professional reports of various file formats (webpage/html, PDF) effectively. 

- Navigating the Analytics Landscape: Understand the current trends in analytics and data technology, along with foundational concepts of cloud computing.

## Target Audience

This course caters to several professionals, including the following groups: 

- Analysts: Ideal for those with access to detailed data who seek to automate professional reports and visualizations using free open-source tools. 

- Managers: Designed for managers looking for inspiration and strategies to boost team productivity in reporting, particularly within budget constraints, or those interested in enhancing their understanding of modern analytics processes.

## Prerequisite(s)

- Some basic level of understanding about Python or programming tools such as R and others. 

  - If you are coming from primarily Excel background and have little experiences in programming-based solutions, please consider starting with "Excel and Python: A Tale of Two Power Tools". As it transitions you nicely from spreadsheet environment to programming environment.

- To fully engage in this course, please ensure you have access to a PC and are prepared to install the necessary open-source tools prior to the seminar. This will allow you to follow along with the hands-on exercises and make the most of the learning experience.