---
title: 'Modern "Excel-erated" Accounting'
---

## Description

Microsoft Excel has been bread-and-butter for almost every single accountant. Its evolution continues fast and furious, more than ever. Dynamic arrays, creating custom functions, lambda functions, importing database data, local linear optimization and of course, AI-powered features when used properly could save you or teams hours/days, deliver amazing outputs, and put focus back on accounting, instead of data readiness. We will dive into a variety of these features together through real-world use cases, hoping that you/your team will be more productive and be inspired to adapt to your accounting workflows. We will end on a higher note about best practices of spreadsheet modelling so that your work is not only effective, but also professional and user-friendly.

## Length

8 hours.

## Key Takeaways 

Upon completion of this course, you will have a good understanding about Microsoft Excel of:

- Dynamic array and dynamic array functions in Microsoft Excel. 

- How to use dynamic array functions to process, manage, and perform advanced operations on data in Excel. 

- How to create custom functions and streamline repetitive yet complex data processing and calucaltions in Excel.

- How to create custom calculations charge up Pivot Table beyond its basic functionalities.

- How to ingest and transform data from a variety of sources (web pages, PDF, database etc.)

- How to leverage AI-powered features (Copilot, Image recongition) to dramatically increase productivity in Microsoft Excel.

- How to use Python in Excel to handle analyses and process data beyond what Excel functions can handle.

- Best practices of professionally spreadsheet modelling. 

## Target Audience

This seminar will benefit the following groups: 

- Analyst(s) who works with detailed data and is frequently tasked with data wrangling and reporting. 

- Manager(s) who seeks inspiration and opportunities to increase their team's reporting productivity with Microsoft Excel, or who aims to enhance their knowledge and literacy to navigate change management as staff begin to leverage advanced and modern features available in Microsoft Excel.

## Prerequisite(s)

To get the most out of this session, prospective audience should have a few years of experience using Microsoft Excel. You should be comfortable with concepts like Pivot Tables, lookups, and basic functions such as SUM and SUMIFS.