---
title: "Excel Accounting with R"
---

## Description

This lab-style seminar provides hands-on experience in completing a advanced Microsoft Excel data project. We are building an interactive budget review solution facilitated by an advanced visualization that is beyond normal Excel reach. Audience will learn about a powerful, popular, free, analytical-first, beginner-friendly language R and even better, how to integrate R right into your Excel workbooks, inspiring you to enhance your accounting Life. 

We will also delve into the mindset of analytics professionals and feel the synergy between analytics and accounting. The seminar will conclude with an overview of the current analytics and technology landscape, highlighting how accountants can pivot/capitalize on these trends. This course is designed to be friendly for those new to analytics.

## Length

8 hours.

## Key Takeaways

Upon completion of this course, you will understand:

- Learn the fundamentals of R: a powerful, free, data-analytics-first programming language.

- Super charge Excel with R: How to create and run R programs in Excel workbooks and supercharge your Excel capability.

- When to use R in Microsoft Excel and when to build an independent R program. 

- Data Processing and Management with R. 

- Advanced Data Visualization Techniques: Discover how to create impactful visualizations with R. 

- Navigating the Analytics Landscape: Understand the current trends in analytics and data technology, along with foundational concepts of cloud computing.

## Target Audience

This course caters to several professional profiles, highlighting key ones here: 

- Analysts: Ideal for those with access to detailed data who seek to enhance Microsoft Excel analytical capabilities and visualization capability using advanced free tools. 

- Managers: Designed for managers looking for inspiration and strategies to boost team productivity (based on Microsoft Excel) in reporting, particularly within budget constraints, or those interested in enhancing their understanding of modern analytics and new possibilities.

## Prerequisite(s)

No previous programming knowledge required. This is beginner friendly session.

To get the most out of this session, you should have a few years of experience using Microsoft Excel. You should be comfortable with concepts like Pivot Tables, lookups, and basic functions such as SUM and SUMIFS.

To fully engage in this course, please ensure you have access to a personal computer (Windows or macOS) and are prepared to install the necessary tools prior to the seminar. This will allow you to follow along with the hands-on exercises and make the most of the learning experience.