---
title: "Infuse Python to Accounting"
---

## Description

This seminar provides hands-on experience in completing a comprehensive accounting project through a modern analytics approach. Audience will learn using Python to streamline a typical accounting task that produces ready-to-distribute outputs (like PDFs, webpages, Excel workbooks), inspiring to dramatically enhance their accounting workflows. 

We will also delve into key mindsets of analytics professionals and feel the synergy between analytics and accounting. The seminar will conclude with an overview of the current analytics and technology landscape, highlighting how accountants can pivot/capitalize on these trends. 

This course is designed for those who have basic level of knowledge about Python or other command-line-driven analytical tools such as R and others.

## Length

8 hours.

## Key Takeaways

Upon completion of this course, you will understand:

- How to set up Python to be productive for data analyss tasks.

- How to work with Python-a powerful, popular, free, general-purposed programming language to import data, process data, visualize data and export outputs, an integrated data analytical process. 

- How to automate workflows with Python, through a practical example of departmental report distribution. 

- Analytics Mindset: Explore essential concepts and key components of successful analytics projects. 

- The current trends in data analytics and data technology, along with foundational concepts of cloud computing.

## Target Audience

This course caters to several professionals, including the following groups: 

- Analysts: Ideal for those with access to detailed data who seek to dramatically increase data processing/cleaning capability, automate professional reports and crafting professional grade data visualizations using free open-source tools. 

- Managers: Ideal for those looking for inspiration and strategies to boost team productivity in reporting, particularly within budget constraints, or those interested in enhancing their understanding of modern analytics and new possibilities.

## Prerequisite(s)

Prospective audience is recommended to have some basic understanding about programming language such as Python, R or others. 

:::{.callout-tip}

If you are coming from primarily Excel background and have little experiences in programming-based solutions, please start with ["Excel and Python - A Tale of Two Power Tools"](/chapters/ExcelPython.qmd). As it transitions you nicely from spreadsheet environment to programming environment.

:::

To fully engage in this course, please ensure you have access to a personal computer (Windows or macOS) and are prepared to install the necessary tools prior to the seminar. This will allow you to follow along with the hands-on exercises and make the most of the learning experience.