---
title: Big Data and Modern Data Platform
subtitle: Overview
---

## Description

Accountants are the most essential force of providing business intelligence and are often tasked to "modernize" or "leverage big data analytics". However, when working with IT specialists or AI engineers/data scientists, unavoidable jargons like "lakehouse", "compute cluster", "data lake" present big barrier to effective collaboration. This session builds a strong literacy of analytical technology and overcome the discomfort. 

We learn about these technical jargons through practical demonstration using a modern data platform, **Microsoft Fabric**, a powerful data platform deeply integrated with **Microsoft Power BI**, and desirable by many organizations that already using Microsoft toolstack such as Azure or Power Platform. Whether you are extending your knowledge beyond Power BI, leading enterprise modernization projects, working with analytics technology specialists, or contemplating on strategic investment choices in analytics/AI, you will walk away with valuable knowledge.

## Length

4 hours

## Key Takeaways

Upon completion of this course, you will understand:

- Key concepts and components of big-data and modern analytics workflows and their common patterns;

- Key concepts and components of data platform and how it supports analytics workflows;

- Key concepts of advanced analytics (e.g. predictive analytics and AIs);

- How predictive analytics and AI work at a high level and how a data platform supports creating these applications;

- Key roles and human talents to build, implement, and support advanced big-data analytics/AI applications;

- How to plan and invest in modernizing enterprise financial analytical capabilities through data platform. 

## Target Audience

You can be:

- Analyst/Staff accountant, who try modernize enterprise reporting, plan to build enterprise analytics applications or, collaborate with technical staff/consultants to build enterprise analytics applications.

- Manager, who would like to plan or lead enterprise modernization efforts on budgeting/planning, reporting, analytics, and process improvements through big data initiatives, more strategically, intentionally and effectively, especially when it comes to collaborating with IT or technical consultants.

## Prerequisite(s)

No prior experience with programming required. Everyone is welcome to join. 