---
title: "Power BI Works for Power Accountants"
---

## Description

This condensed certificate program equips accountants with strong foundation to handle a variety of common accounting tasks. We will go through some in-depth hands-on projects on financial reporting and budget management, **without any extra paid add-ons**. By the end of the course, you will have solid understanding how Power BI works and how to work with Power BI. Even better, you will take away with tangible projects that you have built, either to demonstrate your skills or to reference later. We will also discover best practices for data visualizations and dashboard design. These are critical to effective communicatimg insights, but also are easily and often overlooked. This course is beginner-friendly and in hands-on lab-style. It starts with basics and quickly rises to intermediate/advanced techniques to focus on real world applications.

## Length

20 hours.

## Key Takeaways

Upon completion of this course, you will understand:

- Main concepts about Power BI (Power Query, Data Analytics Expressions, Data Modelling) and how and why they exist to work together
- How to use Power BI to handle a variety of financial tasks such as
  
  - Constructing custom financial statements, 
  - Enabling self-served what-if analyses
  - Managing KPIs  
  - Constructing custom budget reports
  - Conducting variance analyses

- Best practices in data visualizations and dashboard design techniques and how they can make your reports effective and stand out 
- Introduction to relational databases and cloud computing, and why they matter to your Power BI projects
- Analytics engineering mindset and product management mindset and why they matter to your Power BI projects
- Key considerations in planning and in investing about modern enterprise visualization projects. 

## Target Audience

This course appeals to several demographics: 

- **Analysts/staff accountants**, especially who 

  a. are tasked/interested in enhance budget reporting with Power BI and have access to ledger-level details as a data source, 

  b. want to advance skills in developing Power BI report products, or

  c. want to improve effectiveness of data visualization and dashboard desgins;

- **Managers**, especially who

  a. seek inspirations to improve team's budget management productivity with Power BI, 
  
  b. lead modernization projects in FP&A area (financial planning and analysis), 
  
  c. would like to stay relevant with staff/colleagues on designing/implementing enterprise dashboarding projects and effective data visualization techniques, or
  
  d. need to intentionally plan and intelligently invest in modern enterprise dashboarding projects


## Prerequisite(s)

Any level of knowledge about Power BI is welcome. No previous knowledge about Power BI required. This is beginner friendly session.

To get the most out of this session, you should have a few years of experience using Microsoft Excel. You should be comfortable with concepts like Pivot Tables, lookups, and basic functions such as SUM and SUMIFS.

To fully engage in this course, please ensure you have access to a personal computer (Windows or macOS) and are prepared to install the necessary tools prior to the seminar. This will allow you to follow along with the hands-on exercises and make the most of the learning experience.