---
title: "To-Dos, Before Our Session Begins"
---

## Why Chores Before Our Session Even Begins?

This session is an intermediate-level, walk-through-style seminar/lab. To follow along, we need to have the same tools to work with. We are completing setups before our session so that we can dive right into the good stuff in our session. This also identifies whether you have proper equipment for the session. 

***Please ensure all of the setups in the "What Setups Do We Need?" completed before joining the session.***

## What Setups Do We Need? 

1. Personal laptop.

  - Windows OS is a must, as Microsoft Power BI Desktop has no macOS offering.

  - ***Why Personal laptops?***
    
    - Company-managed laptops tend to have restrictive IT policies that tend to prohibit us from installing the tools as we need.

2. Power BI Desktop (see [Get Stared with Poewr BI Desktop](Setup-pbidesktop.qmd))

3. PostgreSQL server (see [Get Started with PostgreSQL](Setup-postgreSQL.qmd))


🎉🎉 **That's it!! That's all the setup we need to get the show going! I look forward to seeing you see the session!**

<!-- This is reused for all accountant Power BI workshop series -->