---
title: "Start with R"
date: 2025-03-01
author: Jianyuan(Andy) Hu
---

## What Is R?

R is ‘GNU S’, a freely available language and environment for statistical computing and graphics which provides a wide variety of statistical and graphical techniques: linear and nonlinear modelling, statistical tests, time series analysis, classification, clustering, etc. Please consult the R project homepage for further information. (https://cran.r-project.org/).

## Why R?

In a nutshell, 4 reasons:

1. R is built for data analyses, it is a data-first language.
2. R is built by analysts and statisticians, not computer scientises, so it is easy for beginners to step into the analytics world.
3. R has a great community support, lots of wisdowm if you need to Q&A
4. R is powerful enough to handle nearly all of your analytics needs, with 20000+ packages available, all open-source, free to use. 

## How to Begin Working with R?

There are 2 parts:

1. We need to install a software that can "understand" R lanugage and command your computer to do things accordingly. This software is called "R", yes the same as the language name "R". You can find it here: [CRAN R Download](https://cran.rstudio.com/).

2. We need to install another software that can help us to be very productive working with R. 

There are many options in this category. The top 2 choices are: 

- RStudio 
  - This is considered as the Go-to tool to work with R, highly recommeded for beginner with R. For maximum beginner friendliness, this is what we will use here.
  - [RStudio Desktop Download Link](https://posit.co/download/rstudio-desktop/)
- Positron 
  - This is still currently in preview, but it will likely be successor to RStudio one day. 
- Visual Studio Code 
  - This excellent to work with multiple programming lanugage environments, but it requires a quite bit setup, so not recommended for beginner. 

At this stage, there are many publicly available walkthroughs to install both of the tools. I will recommend a few here, one for each major personal computer environment. 

- [Walkthrough - Install R and RStudio on Windows 11](https://www.youtube.com/watch?v=H9EBlFDGG4k)
- [Walkthrough - Install R and RStudio on macOS](https://www.youtube.com/watch?v=I5WIMX4LK8M)

Please note that the R version in the referenced videoes might not be as recent as you will see, but the installation process will be the same. 

## Let's GO!

Now, please follow the video walkthroughs above and give it a try to install R and RStudio, so we can get the party started!